%% Auto generate plots for Helix manuscript plotted
% This code regenerates subplots for the publication 
% "Arrested coalescence drives helical coiling and networking of 
% filamentous smectic condensates"
% arXiv 2603.12124 
% https://arxiv.org/abs/2603.12124

% This code and all numerics written by Christopher A. Browne
% Equations modeled herein generated by Christopher A. Browne, 
% Paul G. Severino, and Jacob Z. Cloutier

% All extraneous checks and internal validation plots removed for
% readability and cleanliness of code output.

%% General
clc; clear;

% --- Parameters --- %
K = 40/10^12; % pN -> N
gamma = 300/10^6;%.0115/10^3; % mN/m -> N/m

%% Fig.3F - Ribbon Omega R
% Plot colors
HCol = [124 183 62]/255;
ICol = [170 170 170]/255;

% --- Parameters --- %
R_F_single = 1/10^6; % um -> m
R_L = 4.9/10^9; % nm -> m
l_0 = 100/10^6; % um -> m % arbitrary basis, does not affect results

% ----------- Ribbons ----------- %
Omega_R = linspace(.001,.999,1000);

% - Lengthening by volume conservation - %
S_0 = pi*R_F_single^2; % Convension: single filament
S = R_F_single^2*(pi - acos(1-Omega_R) + (1-Omega_R).*sqrt(1-(1-Omega_R).^2));% Convention: cross sectional area of one ribbon half
V_0 = l_0*S_0; % Convention: single filament
l_l0 = S_0./S; % dimensionless

% - Surface tension - %
A = 4*R_F_single*l_0*l_l0.*(pi - acos(1-Omega_R));
A_0 = 4*R_F_single*l_0*pi;% For 2 filaments (neglect caps)
Fs = gamma*A;
Fs0 = gamma*A_0;
delFs = Fs - Fs0;

% - Elastic energy - %
Fe0 = (2*pi)*(K/8) * l_0 * log(R_F_single/R_L); % for 1 filament
Fe = Omega_R+NaN;
for i = 1:length(Omega_R)
    r_RF = linspace(Omega_R(i)/2+eps,1,1000); % nondimensional radial position
    thetam = asin((1-Omega_R(i)./r_RF));% = pi - acos(1-Ro(i)./r_RF);
    Fe(i) = 2* (K/8) * (l_0*l_l0(i)) * trapz(r_RF,(thetam+pi/2)./r_RF);% first prefactor of 2: angle integral over half of a ribbon half
end
delFe = Fe - 2*Fe0;

figure('Units','Inches','Position',[.5 3 3 2]);hold on; box on;set(gcf,'color','w')
plot([0 Omega_R 1],[0 delFs 0]/V_0,'-','linewidth',1,'DisplayName','Interfacial Energy','color',ICol)
plot([0 Omega_R 1],[0 delFe delFe(end)]/V_0,'-','linewidth',1,'DisplayName','Elastic Energy','color',HCol)
plot([0 Omega_R 1],([0 delFs 0]+[0 delFe delFe(end)])/V_0,'k-','linewidth',1,'DisplayName','Total Energy')
xlabel('$\Omega_\mathrm{R}$','Interpreter','latex','fontsize',12)
ylabel('$\bar{F}_\mathrm{R}-2\bar{F}_\mathrm{F}~\mathrm{(Pa)}$','Interpreter','latex','fontsize',12)


%% Fig. 3G - Ribbon geometric minimum


R_F_single = 1/10^6;%um -> m % note, units irrelevant for this plot
l_0 = 10/10^6; % um -> m
Omega_R = linspace(.01,.99,1000);

% ---------- Ribbons ----------- %
% - Lengthening by volume conservation - %
S_0 = pi*R_F_single^2;
S = R_F_single^2*(pi - acos(1-Omega_R) + (1-Omega_R).*sqrt(1-(1-Omega_R).^2));% cross sectional area of one ribbon half
    % S_Paul = R_F^2*(2*pi - 4*asin(sqrt(Ro/2)) + sin(4*asin(sqrt(Ro/2))));figure;plot(Ro,S-S_Paul,'-k')
V_0 = l_0*S_0;
    % V = S.*l_l0.*l_0; %tested volume conservation
l_l0 = S_0./S;

% - Surface tension - %
A = 4*R_F_single*l_0*l_l0.*(pi - acos(1-Omega_R));
A_0 = 4*R_F_single*l_0*pi;



figure('Units','Inches','Position',[4 3 3 2]);hold on; box on;set(gcf,'color','w')
plot([0 Omega_R 1],[1 A/A_0 1],'-','Color',ICol,'linewidth',1)
plot(Omega_R,l_l0,'-','Color',[62 159 193]/255,'linewidth',1)
plot(Omega_R,(pi - acos(1-Omega_R))/pi,'-','Color',[160 55 149]/255,'linewidth',1)
[val,loc]=min(A/A_0);
plot(Omega_R(loc),val,'.r','markersize',14)


xlabel('$\Omega_\mathrm{R}$','Interpreter','latex','fontsize',12)
ylabel('$A/A_0$','Interpreter','latex','fontsize',12)
set(gca,'yscale','log')
ylim([0.5 2])


%% Fig. 5H - Coil-Ribbon Energy comparison

% ------ Parameters ------- %
RFList=0.5:.05:4; % um % LEFT IN UM here to end of code for float resolution
l_0 = 1000; % um % arbitrary basis, does not affect results
Omega_C = .19;
Omega_R = .37;
% K and gamma defined above in SI

% - Preallocate - %
FIList_Coil =   RFList + NaN;
FHList_Coil =   RFList + NaN;
FIList_Ribbon = RFList + NaN;
FHList_Ribbon = RFList + NaN;
%  ------ Ribbon Energy (for each radius) ------ %

for iRF = 1:length(RFList)
    % --- Parameters --- %
    RF = RFList(iRF);% um

    % - Lengthening by volume conservation - %
    S_0 = pi*RF^2;
    S = RF^2*(pi - acos(1-Omega_R) + (1-Omega_R).*sqrt(1-(1-Omega_R).^2));% Convention: cross sectional area of one ribbon half
    V_0 = l_0*S_0;% Convention: V_0 = volume of one (of the two) filaments; hence ribbon conserves volume of 2*V_0
    l_l0 = S_0./S;

    % - Surface tension - %
    A = 4*RF*l_0*l_l0.*(pi - acos(1-Omega_R));

    % - Elastic energy - %
    r_RF = linspace(Omega_R/2+eps,1,1000);
    thetam = asin((1-Omega_R./r_RF));% = pi - acos(1-Ro(i)./r_RF);
    Fe = (1/8) * (l_0*l_l0) * trapz(r_RF,(thetam+pi/2)./r_RF)...
        *2 ... % angle integral over half of ribbon half
        *2; % 2 ribbon halves (combined basis)

    FIList_Ribbon(iRF)=gamma*A/(2*V_0)*10^6; %[10^6 um/m]
    FHList_Ribbon(iRF)=K*Fe/(2*V_0)*10^12;% [10^12 um^2/m^2]
end

% ----- Coil energy (for each radius) ----- %
for iRF = 1:length(RFList)
    %clc;fprintf(1,'iRF=%d/%d\n',[iRF,length(RFList)]) % UNCOMMENT THIS LINE TO DISPLAY PROGRESS (if many RF being solved)
    resolution=5000; % Numerical resolution for refinement check
    RH = 1.05; % numerical cutoff R_H/R_F
    n=2; % number of filaments in helix
    RF = RFList(iRF);
    RH = RH*RF;
    ds = (1 - Omega_C)*2*RF;
    p = n*ds./sqrt(1-(n*ds/(2*pi*RH))^2);
    theta_p = atan((2*pi*RH)/p);%pitch angle
    phi =  pi/2 - theta_p;%complementary pitch angle definition; used in some equations for ease
    alphaFun = @(psi,p,RF,phi,n) asin( p*(pi/n-psi)/(2*pi*RF*cos(phi)));
    
    psi_guess = linspace(0+eps*10,pi/n-eps*10,10*resolution);
    
    ZP = ( RH + RF*sqrt(1-sin(alphaFun(psi_guess,p,RF,phi,n)).^2)).*sin(psi_guess) - RF*sin(alphaFun(psi_guess,p,RF,phi,n)).*cos(psi_guess)*sin(phi);
    ZN = ( RH - RF*sqrt(1-sin(alphaFun(psi_guess,p,RF,phi,n)).^2)).*sin(psi_guess) - RF*sin(alphaFun(psi_guess,p,RF,phi,n)).*cos(psi_guess)*sin(phi);

    alphaPlot = real(alphaFun(psi_guess,p,RF,phi,n));
    ZP=ZP(alphaPlot<pi/2-10*eps|alphaPlot>pi/2+10*eps);
    ZN=ZN(alphaPlot<pi/2-10*eps|alphaPlot>pi/2+10*eps);
    alphaPlot=alphaPlot(alphaPlot<pi/2-10*eps|alphaPlot>pi/2+10*eps);
    alphaPlotFull = [alphaPlot NaN pi-alphaPlot];
    ZeroFull = real([ZP  NaN ZN]);
    ZeroFull=ZeroFull(alphaPlotFull<pi/2-10*eps|alphaPlotFull>pi/2+10*eps);
    alphaPlotFull=alphaPlotFull(alphaPlotFull<pi/2-10*eps|alphaPlotFull>pi/2+10*eps);
    locs = find([diff(sign(ZeroFull)) 0]~=0);
    alpha_O = real(alphaPlotFull(locs(1)));
    alpha_i = real(alphaPlotFull(locs(end)));
    
    theta_m_approx = asin(1-Omega_C);
    alpha_O_rec = alpha_O;
   
    % Check for volume formula falling outside of applicability range
    if sqrt((p/2/pi)^2+RH^2)/RF<1
        fprintf(1,'Warning for volume formula for RH = %$.1f, Omega = %.01f\n',[RH,Omega_C])
    end

    CrossProductNormOuter = @(rho,alpha) rho.^2*RH*cos(alpha)/sqrt((p/2/pi)^2+RH^2) +...
        rho*sqrt((p/2/pi).^2+RH.^2);

    % - Area - %
    rho = RF;
    if RH == 1
        alphaOuter = 0:pi/resolution:alpha_O; % only outside, one half of alpha domain
        alphaInner=[];disp('Check error in setting alphaInner = []')
    else
        alphaOuter = 0:pi/resolution:alpha_O;
        alphaInner = alpha_i:pi/resolution:pi;% Inside and outside, one half of alpha domain
    end

    if alpha_O<pi/2
        A = (trapz(alphaOuter,CrossProductNormOuter(rho,alphaOuter))...
            +0*trapz(alphaInner,CrossProductNormOuter(rho,alphaInner)))...
            *(2*pi)...% for one pitch (theta = 0 to 2 pi)
            *2 ...%only integrated half of alpha
            *2;% for both helices in double coil
    else
        A = (trapz(alphaOuter(alphaOuter<pi/2),CrossProductNormOuter(rho,alphaOuter(alphaOuter<pi/2)))...
            +trapz(alphaOuter(alphaOuter>=pi/2),CrossProductNormOuter(rho,alphaOuter(alphaOuter>=pi/2)))...
            +0*trapz(alphaInner,CrossProductNormOuter(rho,alphaInner)))...
            *(2*pi) ...% for one pitch (theta = 0 to 2 pi)
            *2 ...%only integrated half of alpha
            *2;% for both helices in double coil         
    end
    
    % - Volume - % 
    Volume_Integrand = @(rho,alpha,p,RH) rho.*sqrt((p/2/pi)^2+RH^2) + ...
        rho.^2.*cos(alpha)*RH/sqrt((p/2/pi)^2+RH^2);

    alpha = linspace(0,pi,resolution);
    Result1 = alpha.*0;
    deltaAlpha=(alpha_i-alpha_O)/2;
    avAlpha=(alpha_i+alpha_O)/2;

    for iAlpha = 1:length(alpha)
        if (alpha(iAlpha)>alpha_O && alpha(iAlpha)< alpha_i )% || (alpha(iAlpha)>2*pi-alpha_i && alpha(iAlpha)< 2*pi-alpha_O )
            rho = 0:(RF/resolution):(RF*cos(deltaAlpha)/cos(abs(alpha(iAlpha)-avAlpha)));
        else
            rho = 0:(RF/resolution):RF;
        end
        if length(rho)>1
            Result1(iAlpha) = trapz(rho,Volume_Integrand(rho,alpha(iAlpha),p,RH));
        end
    end
    V = trapz(alpha,Result1) ...
        *(2*pi) ...% (theta = 0 to 2 pi)
        *2 ...%only integrated half of alpha
        *2;% 2 coils

    %%% - Simplified Elasticity - %%%  
    % Needs to use approximate alpha to solve integral bounds all
    % along parabola; otherwise, need to re-solve alpha_o and alpha_i
    % for each rho value x resolution
    r_RF = linspace(Omega_C+eps,1,100);
    integral1 = r_RF + NaN;
    for rr = 1:length(r_RF)
        theta_m_C = asin(1-Omega_C./r_RF(rr));% USING APPROX ALPHA

        alpha = [linspace(0+eps,theta_m_C-eps,100)'; linspace(pi-theta_m_C+eps,pi-eps,100)'];
        Rhp = RH + cos(alpha);
        H2 = (2*(1-Omega_C)/(pi*cos(theta_p)) + 2*pi*cot(theta_p) + r_RF(rr).*cos(alpha)).^-1;
        Hav = 1/2*(1./(r_RF(rr)) + H2)/RF;
        integral1(rr) = trapz(alpha,Hav.^2.*Volume_Integrand(RF*r_RF(rr),alpha,p,RH));
    end
    Fe = trapz(r_RF*RF,integral1)... % Integral term
        *(2*pi) ...% (theta = 0 to 2 pi)
        *2 ...%only integrated half of alpha
        *2;% 2 coils
    
    FIList_Coil(iRF)=gamma*(A./V)*10^6;%[10^6 um/m]
    FHList_Coil(iRF)=K*(Fe./V*10^12); %[10^12 um^2/m^2]
end

% ----- Plot reduction from Ribbon to Coil ----- %
figure('Units','Inches','Position',[7.5 3 3 2]);hold on; box on;set(gcf,'color','w')
plot(RFList,(FIList_Coil-FIList_Ribbon),'color',ICol,'linewidth',1);
plot(RFList,(FHList_Coil-FHList_Ribbon),'color',HCol,'linewidth',1);
plot(RFList,(FHList_Coil-FHList_Ribbon+FIList_Coil-FIList_Ribbon),'k','linewidth',1);
ylabel('$\bar{F}_\mathrm{C}-\bar{F}_\mathrm{R}~\mathrm{(Pa)}$','interpreter','latex','fontsize',10)
xlabel('$R_\mathrm{F}~(\mathrm{\mu m})$','interpreter','latex','fontsize',10)
xlim([0.5 4])
ylim([-200 150])

